### ISSUE TITLE
使用多布局，其中一个布局用这个后滑动不过去会回弹 使用代码可以跳下一页

### ISSUE THREAD

**Issue by bjy520** [shenbengit/PagerGridLayoutManager#10]
我在使用brvah 放的BaseMultiItemQuickAdapter 这个的多布局  然后其中的一个布局是来分页 当嵌套的时候会发生滑动不到下一页的问题，我看前面说图片原因  我这也设置固定大小了 不行 去掉图片也不能滑动

**Comment by shenbengit** [comment]
你是RecyclerView嵌套RecyclerView吗？初步判断应该是滑动冲突的问题。说明下内外层的滑动方向，方便的话贴下相关代码。我试着复现一下。

**Comment by bjy520** [comment]
![image](https://user-images.githubusercontent.com/18107295/147336879-47dca74d-1296-4880-818b-91b36859dd40.png)
是有viewpager  里面用一个ARecyclerView  是竖着的    ARecyclerView 使用多布局  只放了recycleview    这个recycleview   就是上边的代码

**Comment by shenbengit** [comment]
![1](https://user-images.githubusercontent.com/24364422/147378474-6aea2088-f5bc-4abf-96bf-f996ffda0964.gif)
你要的是这个效果吗？我测试了没问题。layoutManager.setHandlingSlidingConflictsEnabled(true);才会处理滑动冲突，你设置成false了。如果遇到滑动冲突尝试使用LinearLayoutManager看下是否也存在。一般来说滑动冲突需要自己处理。LayoutManager只负责布局。看下[NestedRecyclerViewFragment](https://github.com/shenbengit/PagerGridLayoutManager/blob/master/app/src/main/java/com/shencoder/demo/fragment/NestedRecyclerViewFragment.java)。

**Comment by bjy520** [comment]
Uploading E84C43B999A1F362E748A40C22BDAE14.mp4…
ayoutManager.setHandlingSlidingConflictsEnabled(true)  这个我这设置true也是这样的  如视频这样  然后我直接代码
 rvList.post {
                        pagerGridLayoutManager.scrollToPagerIndex(1)
                    }
                    让他去第二页就可以   不过也很难滑动到第一页  滑动到第一页后也划不到第二页了

**Comment by shenbengit** [comment]
视频上传失败了。如果是我上面图的效果，请参考。库中自带的滑动冲突解决方案若不满足需求，那要自己实现了。

**Comment by bjy520** [comment]
#11   更新后就好了  应该是i这个影响了
