### ISSUE TITLE
当 item 刷新的时候无法滚动，是用场景是列表的进度更新

### ISSUE THREAD

**Issue by Wesley254619** [shenbengit/PagerGridLayoutManager#11]

**Comment by shenbengit** [comment]
请展示实现效果或相关代码。未能明白您的意思。

**Comment by Wesley254619** [comment]
场景是这样的，类似于手机应用市场里面的 App 批量更新，我们做的是两行两列，一页展示四个，然后左右滑动翻页。点击更新后需要在 item 上展示下载进度。

**Comment by Wesley254619** [comment]
[/Users/kuanghu/Download/1640494755734539.mp4](url)

**Comment by shenbengit** [comment]
是存在这个问题。调用Adapter中notifyXXX()相关方法时会间接调用LayoutManager.onLayoutChildren()，而我在onLayoutChildren()处理的方式为绘制上次页的且总以左上(0,0)开始布局，没有记录上次滑动的位置。后面会修复这个问题。

**Comment by shenbengit** [comment]
试下v1.1.3
