### ISSUE TITLE
设置clipToPadding=false后布局bug

### ISSUE THREAD

**Issue by jin123d** [shenbengit/PagerGridLayoutManager#13]
```
<androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_gift"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:paddingLeft="12dp"
        android:paddingRight="12dp" />
```
两个分页之间的间距没有把padding计算进去

图中**红色箭头黑框**为上一页礼物的选中框，结果翻页的时候出现到了第二页。

![image](https://user-images.githubusercontent.com/11838111/149619592-51ccbf0b-9f69-45e5-bce7-ff330807e149.png)

**Comment by shenbengit** [comment]
你这个应该和 #9 一样的情况，我无法复现，如果方便可以将复现代码发到我的邮箱，714081644@qq.com。

**Comment by jin123d** [comment]
> 你这个应该和 #9 一样的情况，我无法复现，如果方便可以将复现代码发到我的邮箱，[714081644@qq.com](mailto:714081644@qq.com)。

这个边框是上一个页面的，应该和他的不一样。

**Comment by shenbengit** [comment]
这不能算是一个bug，clipToPadding=false 就已经允许子View绘制到父View的padding里面，你可以先使用ItemDecoration来实现代替这个效果，我将在版本去兼容这个问题。

**Comment by jin123d** [comment]
> 这不能算是一个bug，clipToPadding=false 就已经允许子View绘制到父View的padding里面，你可以先使用ItemDecoration来实现代替这个效果，我将在版本去兼容这个问题。

好的。目前来看直接跳到页面就没这个问题，滑动的时候就有。

**Comment by shenbengit** [comment]
试下v1.1.5。

**Comment by jin123d** [comment]
> 试下v1.1.5。

效果很OK，谢谢大佬！
