### ISSUE TITLE
在viewpager中用rv的父布局是RelativeLayout的话会报RecyclerView's width and height must be exactly

### ISSUE THREAD

**Issue by qq517103430** [shenbengit/PagerGridLayoutManager#14]
在viewpager中用rv的父布局是RelativeLayout的话会报RecyclerView's width and height must be exactly

**Comment by shenbengit** [comment]
RecyclerView的宽高度需要指定。

**Comment by qq517103430** [comment]
指定了啊，你直接用你demo里viewpageractivity那个，把第一个fragment里的根布局由LinearLayout改成RelativeLayout就能复现

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/159014202-fbc53c2f-2547-4b90-ab08-9c9493b53b84.png)
读一下RelativeLayout源码就好了，这个是源码决定的，目前的本框架的局限性还无法解决这个问题，或者使用ConstraintLayout代替RelativeLayout。

**Comment by shenbengit** [comment]
v1.1.8 做了兼容处理
