### ISSUE TITLE
Rtl

### ISSUE THREAD

**Issue by EdwinSmartBoy** [shenbengit/PagerGridLayoutManager#16]
是否能够支持一下rtl

**Comment by shenbengit** [comment]
可以考虑支持，你是想要什么效果？是排列方式从右到左还是滑动方向也从右到左滑动。可以搞个示例图看一下。

**Comment by EdwinSmartBoy** [comment]
中东地区的阅读习惯是从右往左，滑动方向也是从右往左滑动，item数据也是从右往左排列。

**Comment by shenbengit** [comment]
好的，我抽空添加一下。

**Comment by EdwinSmartBoy** [comment]
> 好的，我抽空添加一下。

非常感谢。

**Comment by shenbengit** [comment]
RTL已经支持，详见[构造方法](https://github.com/shenbengit/PagerGridLayoutManager/blob/a9e7d3d6d445f79f0a0b9cf69ec9eee7d53ab24d/pagergridlayoutmanager/src/main/java/com/shencoder/pagergridlayoutmanager/PagerGridLayoutManager.java#L196) 和 [setReverseLayout](https://github.com/shenbengit/PagerGridLayoutManager/blob/a9e7d3d6d445f79f0a0b9cf69ec9eee7d53ab24d/pagergridlayoutmanager/src/main/java/com/shencoder/pagergridlayoutmanager/PagerGridLayoutManager.java#L839)，要注意的是水平方向反向是排列顺序和滑动放向都反向，垂直方向仅排列顺序反向，这与LinearLayoutManager不同。

**Comment by EdwinSmartBoy** [comment]
非常感谢！
