### ISSUE TITLE
分页后每页都填充满

### ISSUE THREAD

**Issue by mr-xujianbao** [shenbengit/PagerGridLayoutManager#17]
如果希望分页后每页都填充满，应该怎么实现

**Comment by shenbengit** [comment]
没明白你的意思？

**Comment by mr-xujianbao** [comment]
设置一行3列，现在总共有4个item，第一页是1、2、3，第二页是2、3、4，每一页都是3项

**Comment by shenbengit** [comment]
此库实现不了，自定义SnapHelper +LinearLayoutManager 应该就可以实现了。
