### ISSUE TITLE
依赖不下来这个库

### ISSUE THREAD

**Issue by huangShan-gitHub** [shenbengit/PagerGridLayoutManager#18]
AS会报提示Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

**Comment by shenbengit** [comment]
这个是你gradle的问题，和本库无关系。

**Comment by shenbengit** [comment]
或者尝试升级gradle

**Comment by huangShan-gitHub** [comment]
我的gradle是7.2版本的，要最低升级到多少才支持呢？

**Comment by shenbengit** [comment]
新建项目，看看能不能单独引入。
