### ISSUE TITLE
作者您好，垂直滚动的情况下，元素显示如何做到先从上到下，再从左到右呢？

### ISSUE THREAD

**Issue by WangkeqiangS** [shenbengit/PagerGridLayoutManager#21]
我看了1.0.6的分支，似乎只支持了水平滚动，请问我该在哪里修改一下呢？

**Comment by shenbengit** [comment]
https://github.com/shenbengit/PagerGridLayoutManager/blob/f9dc4f11cf8ee46020f47edf0cfc50d9502f4799/pagergridlayoutmanager/src/main/java/com/shencoder/pagergridlayoutmanager/PagerGridLayoutManager.java#L955

代码在这，你可以fork项目自己改下，后面抽时间我把这部分逻辑抽出来，子类可重写实现。

**Comment by WangkeqiangS** [comment]
这部分是否可以提供一个方法进行调用实现呢？

**Comment by shenbengit** [comment]
排列顺序目前是写死的，不支持自定义。layoutChildren()，是需要开发者自己实现的。最近比较忙碌，着急的话，需要自己先自行实现。

**Comment by shenbengit** [comment]
欢迎PR

**Comment by WangkeqiangS** [comment]
好的，我先看看，谢谢回馈
