### ISSUE TITLE
oppo手机上滑动冲突处理不稳定

### ISSUE THREAD

**Issue by Kunsan16** [shenbengit/PagerGridLayoutManager#23]
viewpager2上，fragmentA和fragmentB，fragmentB上是recyclerview，并使用该layoutmanger,有多页可左右滑动。有时往右滑动会直接滑到fragmentA，oppo出现该问题，华为手机上正常

**Comment by shenbengit** [comment]
demo是否可以复现，可复现的话，录个视频看下，你可以先layoutManager.setHandlingSlidingConflictsEnabled(false); 禁用库里的滑动冲突，自己先处理下。晚点我看下。

**Comment by Kunsan16** [comment]
你好！我另外写个demo试是正常的，应该是我项目代码问题，正在排查，您可以关闭此issue。
顺便说下我项目中问题大概是：
左滑时，在`MotionEvent.ACTION_MOVE`中
```java
        final int dx = x - mInitialTouchX;
        final int dy = y - mInitialTouchY;
```
`dx`和`dy`在我左滑的时候都为0，导致允许了viewpager2拦截事件，直接滑到fragmentA，目前我自己继承recyclerview，先单独处理这种情况。
