### ISSUE TITLE
clipChildren 问题

### ISSUE THREAD

**Issue by protectedMan** [shenbengit/PagerGridLayoutManager#24]
设置了clipChildren=false 后 recyleview以外的区域也透明展示出来了, 但是我还想实现recyleview的item可以drag出来的效果需要设置clipChildren=false , 该如何是好.
这可能不是本库的问题, 但是希望作者如果有解决方案能帮个忙

视频见:
![image](https://user-images.githubusercontent.com/17565737/235087729-71aabc9d-e312-4943-9516-04d6d38cb7b3.png)

**Comment by protectedMan** [comment]
https://user-images.githubusercontent.com/17565737/235088325-b5a93302-bc2b-4353-8217-17a47a997637.mp4

**Comment by shenbengit** [comment]
> 设置了clipChildren=false 后 recyleview以外的区域也透明展示出来了, 但是我还想实现recyleview的item可以drag出来的效果需要设置clipChildren=false , 该如何是好. 这可能不是本库的问题, 但是希望作者如果有解决方案能帮个忙
> 
> 视频见: ![image](https://user-images.githubusercontent.com/17565737/235087729-71aabc9d-e312-4943-9516-04d6d38cb7b3.png)

recyleview以外的区域也透明展示出来了，这个在视频里体现了吗？没看出来啊

**Comment by protectedMan** [comment]
红线是recyleivew区域
![image](https://user-images.githubusercontent.com/17565737/236092280-f0caecc3-a68e-46da-8fbe-f91d1eb15007.png)

**Comment by shenbengit** [comment]
实际效果是啥样的，你这是弹出框？布局xml 看下。

**Comment by protectedMan** [comment]
写了个简单的demo你方便时候看下 🙏
https://github.com/protectedMan/RecyclerViewDrag.git

activity_folder2.xml

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/236364046-f527dbd9-1b73-472d-adfe-7527b070a9d6.png)
你的意思是这部分是多余的吗？

**Comment by protectedMan** [comment]
是的

**Comment by shenbengit** [comment]
你先试试 使用clipToPadding 能不能达到类似的效果， #13
