### ISSUE TITLE
快速滑动时，onPagerIndexSelected只会回调一次

### ISSUE THREAD

**Issue by sulovely** [shenbengit/PagerGridLayoutManager#27]
快速滑动时，比如从第0页滑到第6页，onPagerIndexSelected回调只会在滑动停止的时候会回调最后一页，导致指示器不会显示中间1,2,3,4,5页的状态
[device-2023-10-12-164952.webm](https://github.com/shenbengit/PagerGridLayoutManager/assets/46919682/72749360-98a6-4b37-8961-8ce988ba4faa)

**Comment by sulovely** [comment]
[](url)

**Comment by shenbengit** [comment]
只有在滚动完成时才会去计算当前页码位置。滚动中不计算。
