### ISSUE TITLE
MagicIndicator嵌套vp2 分页滚动会错乱

### ISSUE THREAD

**Issue by zyj5127** [shenbengit/PagerGridLayoutManager#28]
你好，代码可以见附件，错乱视频如视频
[未命名文件夹.zip](https://github.com/shenbengit/PagerGridLayoutManager/files/13901809/default.zip)

**Comment by zyj5127** [comment]
是不支持这么做吗？必须嵌套 fragment 来做吗

**Comment by shenbengit** [comment]
视频没看出来什么问题，滑动冲突的话可以自己处理。不使用框架内默认实现的即可。
