### ISSUE TITLE
在中间页往后快速滑动一小段距离，结果会滑到上一个页去

### ISSUE THREAD

**Issue by dnfer** [shenbengit/PagerGridLayoutManager#5]
![QQ图片20211101142646](https://user-images.githubusercontent.com/25897470/139630593-5c9b685c-b20a-4a44-a185-92f49c76e3d1.png)
滑动到上一页去了。
![QQ图片20211101142837](https://user-images.githubusercontent.com/25897470/139630724-68671c0b-e5f8-4ad5-82a1-f961e681caca.png)
请问这个怎么改？

**Comment by shenbengit** [comment]
请使用v1.0.1。
