### ISSUE TITLE
条目很多的时候，调用smoothScrollToNextPager经常出现无法滑动到下一页

### ISSUE THREAD

**Issue by wayneleo** [shenbengit/PagerGridLayoutManager#6]

**Comment by shenbengit** [comment]
请提供复现代码及复现经过，我测试1000条数据，未出现你描述的问题。
PagerGridLayoutManager.smoothScrollToNextPager()这个方法只能在RecyclerView静止的时候才有效。

`    public void smoothScrollToPrePager() {
        if (!isIdle()) {//RecyclerView 是否为静止状态
            return;
        }
        smoothScrollToPagerIndex(mCurrentPagerIndex - 1);
    }`

**Comment by wayneleo** [comment]
3排3列 每页9条数据，通过handler发送4秒延迟消息，handleMessage中调用smoothScrollToNextPager实现自动循环滚动，在onPagerIndexSelected回调中判断是最后一页就调用scrollToPagerIndex(0)切换到第一页，如此循环就会出现没法切换

**Comment by shenbengit** [comment]
![1](https://user-images.githubusercontent.com/24364422/140604637-f5644c10-8408-4715-aac0-f882218d6bf6.gif)
是这个效果吗？我直接用demo模拟的 ，没复现。
贴一下你的代码吧
