### ISSUE TITLE
RecyclerView ImageView wrap_content 滑动失效问题。

### ISSUE THREAD

**Issue by huanghongfu** [shenbengit/PagerGridLayoutManager#7]

**Comment by shenbengit** [comment]
请具体说明复现过程。

**Comment by giantbing** [comment]
在adapter中使用了glide 加载网络图片时 可复现此问题

**Comment by shenbengit** [comment]
好的 我测试一下

**Comment by shenbengit** [comment]
@giantbing 问题已经复现了，原因是Glide在加载图片时偶发导致了LayoutManager.onMeasure()->LayoutManager.onLayoutChildren()被调用。目前的解决方案请尝试先固定ImageView的宽高，或Glide加载时指定宽高，我将在下个版本修复这个问题。

**Comment by shenbengit** [comment]
https://github.com/bumptech/glide/issues/2373

**Comment by duanjiao-a** [comment]
我在recyclerView中指定了宽高，但是没有效果。仍然会复现此问题

**Comment by shenbengit** [comment]
不是RecyclerView的宽高，是item layout 中ImageView的宽高。可以看下[GlideActivity](https://github.com/shenbengit/PagerGridLayoutManager/blob/master/app/src/main/java/com/shencoder/demo/activity/GlideActivity.java)。

**Comment by shenbengit** [comment]
fixed.  v1.1.3
